### ISSUE TITLE
Training on AWS and serving on local mode

### ISSUE THREAD

**Issue by DreamyKten** [aws-samples/amazon-sagemaker-local-mode#11]
Hi,
Can I train on AWS sagemaker and serve my model in local mode ?

Thank you

**Comment by eitansela** [comment]
You can train in Amazon SageMaker and deploy on IoT Devices, K8S Cluster, or any other infrastructure that you want.
[This is a nice example](https://github.com/aws-samples/aws-lambda-docker-serverless-inference/tree/main/tensorflow-train-in-sagemaker-deploy-with-lambda) that shows how to train a TensorFlow algorithm in SageMaker, inference with AWS Lambda.
